/*
 *  GameEvents.h
 *  AlienFrontiers
 *
 *  Created by Clint Herron on 2/28/11.
 *  Copyright 2011 HanClinto Games LLC. All rights reserved.
 *
 */

#define EVENT_ORIENTATION_CHANGED @"UIDeviceOrientationDidChangeNotification"

#define EVENT_SHIPS_ROLLED      @"SHIPS ROLLED" // Fired when ships are rolled (both initial, and with Temporal Warper)
#define EVENT_SHIP_ROLLED       @"SHIP ROLLED" // Fired whenever a single ship is rolled (initial and temporal warper)
#define EVENT_SHIP_CHANGED		@"DICE CHANGED" // Fired whenever the value of a ship's face changes
#define EVENT_SHIP_DOCK			@"SHIP DOCK" 
#define EVENT_SHIP_DESTROY		@"SHIP DESTROY"
#define EVENT_SHIP_ACTIVATE		@"SHIP ACTIVATE"
#define EVENT_SHIPS_DOCKED      @"SHIPS DOCKED"
#define EVENT_RESOURCES_CHANGED	@"RESOURCES CHANGED"
#define EVENT_FACILITY_ACTIVATE @"FACILITY ACTIVATE"
#define EVENT_NEXT_PLAYER		@"NEXT PLAYER"
#define EVENT_NEXT_TURN         @"NEXT TURN"
#define EVENT_FIELD_CHANGED     @"FIELD CHANGED"
#define EVENT_LOG_ENTRY         @"LOG ENTRY"
#define EVENT_STATE_RELOAD      @"STATE RELOAD"

#define EVENT_ITEM_TOUCHED      @"ITEM TOUCHED"

#define EVENT_UNDO_CHANGED      @"UNDO CHANGED"

#define EVENT_COLONIES_CHANGED  @"COLONIES CHANGED"
#define EVENT_LAUNCH_COLONY     @"LAUNCH COLONY"

// Raiding
#define EVENT_BEGIN_RAID        @"BEGIN RAID"
#define EVENT_FINISH_RAID       @"FINISH RAID"

#define EVENT_AI_TICK           @"AI TICK"

#define EVENT_BEGIN_CHOOSE_DISCARD  @"BEGIN CHOOSE DISCARD"

#define EVENT_GAME_OVER         @"GAME OVER"

#define EVENT_COLONIST_HUB_ADVANCE @"COLONIST HUB ADVANCE"
#define EVENT_MARKET_PRICE_CHANGED @"MARKET PRICE CHANGED"

#define EVENT_ARTIFACT_CREDIT_CHANGED	@"ARTIFACT CREDIT CHANGED"
#define EVENT_ARTIFACT_SHUFFLES_CHANGED @"ARTIFACT SHUFFLES CHANGED"
#define EVENT_ARTIFACT_CARDS_CHANGED    @"ARTIFACT CARDS CHANGED"

#define EVENT_CARD_TAPPED				@"CARD TAPPED"

// Selections
#define EVENT_SHIP_SELECTED		@"SHIP SELECTED"
#define EVENT_REGION_SELECTED   @"REGION SELECTED"
#define EVENT_CARD_SELECTED     @"CARD SELECTED"

// Potential
#define EVENT_SHIP_POTENTIAL    @"SHIP POTENTIAL"
#define EVENT_REGION_POTENTIAL	@"REGION POTENTIAL"

// GUI events
#define GUI_EVENT_QUEUED_SELECTION_CHANGED	@"QUEUED SELECTION CHANGED"
#define GUI_EVENT_QUEUE_CHANGED				@"QUEUE CHANGED"
#define GUI_EVENT_QUEUE_SELECT_ITEM         @"QUEUED SELECT ITEM"
//#define GUI_EVENT_HINT_CHANGED				@"HINT CHANGED"

#define GUI_EVENT_FX_FLARE                  @"FX FLARE"

#define GUI_EVENT_BUTTON_CLICK              @"GUI BUTTON CLICK"

#define EVENT_USE_PLASMA_CANNON             @"USE PLASMA CANNON"
#define EVENT_USE_BOOSTER_POD               @"USE BOOSTER POD"
#define EVENT_USE_STASIS_BEAM               @"USE STASIS BEAM"
#define EVENT_USE_POLARITY_DEVICE           @"USE POLARITY DEVICE"
#define EVENT_USE_GRAVITY_MANIPULATOR       @"USE GRAVITY MANIPULATOR"
#define EVENT_USE_DATA_CRYSTAL              @"USE DATA CRYSTAL"
#define EVENT_USE_ORBITAL_TELEPORTER        @"USE ORBITAL TELEPORTER"

#define EVENT_DISCARD_PLASMA_CANNON         @"DISCARD PLASMA CANNON"
#define EVENT_DISCARD_BOOSTER_POD           @"DISCARD BOOSTER POD"
#define EVENT_DISCARD_STASIS_BEAM           @"DISCARD STASIS BEAM"
#define EVENT_DISCARD_POLARITY_DEVICE       @"DISCARD POLARITY DEVICE"
#define EVENT_DISCARD_GRAVITY_MANIPULATOR   @"DISCARD GRAVITY MANIPULATOR"
#define EVENT_DISCARD_DATA_CRYSTAL          @"DISCARD DATA CRYSTAL"
#define EVENT_DISCARD_ORBITAL_TELEPORTER    @"DISCARD ORBITAL TELEPORTER"
#define EVENT_DISCARD_TEMPORAL_WARPER       @"DISCARD TEMPORAL WARPER"


/*
#define EVENT_SHIP_ROLL			@"BLASTOFF"
#define EVENT_SHIP_DOCK			@"IN THE PIPE, FIVE BY FIVE"
#define EVENT_SHIP_DESTROY		@"TURN AND BURN"
#define EVENT_DICE_CHANGED		@"LET'S ROCK!!!"
#define EVENT_RESOURCES_CHANGED	@"BIG MONEY, BIG PRIZES!"
#define EVENT_SHIP_SELECTED		@"I HAVE BEEN CHOSEN!"

*/
